<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Mukim;
use App\Models\Village;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            [
                'name' => 'Brunei-Muara',
                'mukim' => [
                    [
                        'name' => 'Daerah Brunei dan Muara',
                        'village' => [
                            ['name' => 'Peti Surat 01 hingga 500'],
                            ['name' => 'Peti Surat 501 hingga 1000'],
                            ['name' => 'Peti Surat 1001 hingga 1500'],
                            ['name' => 'Peti Surat 1501 hingga 2000'],
                            ['name' => 'Peti Surat 2001 hingga 2500'],
                            ['name' => 'Peti Surat 2501'],
                        ],
                    ],
                    [
                        'name' => 'Jabatan Perdana Menteri',
                        'village' => [
                            ['name' => 'Jabatan Audit'],
                            ['name' => 'Jabatan Biro Kawalan Narkotik'],
                            ['name' => 'Jabatan Biro Mencegah Rasuah'],
                            ['name' => 'Jabatan Keselamatan Dalam Negeri'],
                            ['name' => 'Jabatan Penerangan'],
                            ['name' => 'Jabatan Perkhidmatan Awam'],
                            ['name' => 'Jabatan Perkhidmatan Pengurusan'],
                            ['name' => 'Majlis-Majlis Mesyuarat Negara '],
                            ['name' => 'Mufti Kerajaan Brunei '],
                            ['name' => 'Polis Di Raja Brunei'],
                            ['name' => 'Pusat Tahanan'],
                            ['name' => 'Radio Televisyen Brunei'],
                            ['name' => 'Suruhanjaya Perkhidmatan Awam'],
                            ['name' => 'Unit Petroleum'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Hal Ehwal Dalam Negeri',
                        'village' => [
                            ['name' => 'Jabatan Daerah Brunei Muara'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Pertahanan',
                        'village' => [
                            ['name' => 'Kementerian Pertahanan'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Gadong A',
                        'village' => [
                            ['name' => 'Kampong Katok'],
                            ['name' => 'Kampong Rimba'],
                            ['name' => 'Kampong Tungku'],
                            ['name' => 'RPN Kampong Rimba'],
                            ['name' => 'STKRJ Kampong Katok A'],
                            ['name' => 'STKRJ Kampong Rimba'],
                            ['name' => 'STKRJ Kampong Tungku Area 1'],
                            ['name' => 'STKRJ Kampong Tungku Area 2'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Gadong B',
                        'village' => [
                            ['name' => 'Kampong Beribi'],
                            ['name' => 'Kampong Kiarong'],
                            ['name' => 'Kampong Kiulap'],
                            ['name' => 'Kampong Mata-Mata'],
                            ['name' => 'Kampong Menglait'],
                            ['name' => 'Kampong Pengkalan Gadong'],
                            ['name' => 'Kampong Perpindahan Mata-mata'],
                            ['name' => 'STKRJ Katok B'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Berakas A',
                        'village' => [
                            ['name' => 'Kampong Anggerek Desa'],
                            ['name' => 'Kampong Burong Pingai Berakas'],
                            ['name' => 'Kampong Jaya Bakti'],
                            ['name' => 'Kampong Jaya Setia'],
                            ['name' => 'Kampong Lambak'],
                            ['name' => 'Kampong Lambak Kiri'],
                            ['name' => 'Kampong Orang Kaya Besar Imas'],
                            ['name' => 'Kampong Pancha Delima'],
                            ['name' => 'Kampong Pengiran Siraja Muda Delima Satu'],
                            ['name' => 'Kampong Pulaie'],
                            ['name' => 'Kampong Serusop'],
                            ['name' => 'Kampong Terunjing'],
                            ['name' => 'Kawasan Jabatan-Jabatan dan Perumahan Kerajaan'],
                            ['name' => 'Perkhemahan Berakas'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Berakas B',
                        'village' => [
                            ['name' => 'Kampong Lambak Kanan'],
                            ['name' => 'Kampong Madang'],
                            ['name' => 'Kampong Manggis'],
                            ['name' => 'Kampong Salambigar'],
                            ['name' => 'Kampong Sungai Akar'],
                            ['name' => 'Kampong Sungai Hanching'],
                            ['name' => 'Kampong Sungai Orok'],
                            ['name' => 'Kampong Sungai Tilong'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Burong Pingai Ayer',
                        'village' => [
                            ['name' => 'Kampong Burong Pingai Ayer'],
                            ['name' => 'Kampong Lurong Dalam'],
                            ['name' => 'Kampong Pandai Besi A'],
                            ['name' => 'Kampong Pandai Besi B'],
                            ['name' => 'Kampong Pekan Lama'],
                            ['name' => 'Kampong Pengiran Setia Negara'],
                            ['name' => 'Kampong Sungai Pandan A'],
                            ['name' => 'Kampong Sungai Pandan B'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kianggeh',
                        'village' => [
                            ['name' => 'Diplomatic Enclave Area'],
                            ['name' => 'Kampong Berangan'],
                            ['name' => 'Kampong Kianggeh'],
                            ['name' => 'Kampong Kumbang Pasang'],
                            ['name' => 'Kampong Melabau'],
                            ['name' => 'Kampong Parit'],
                            ['name' => 'Kampong Pusar Ulak'],
                            ['name' => 'Kampong Tasek Lama'],
                            ['name' => 'Kampong Tumasek'],
                            ['name' => 'Kampong Tungkadeh'],
                            ['name' => 'Pusat Bandar'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kilanas',
                        'village' => [
                            ['name' => 'Kampong Bengkurong'],
                            ['name' => 'Kampong Bunut'],
                            ['name' => 'Kampong Bunut Perpindahan'],
                            ['name' => 'Kampong Burong Lepas'],
                            ['name' => 'Kampong Kilanas'],
                            ['name' => 'Kampong Jangsak'],
                            ['name' => 'Kampong Madewa'],
                            ['name' => 'Kampong Sinarubai'],
                            ['name' => 'Kampong Tanjong Bunut'],
                            ['name' => 'Kampong Tasek Meradun'],
                            ['name' => 'Kampong Telanai'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kota Batu',
                        'village' => [
                            ['name' => 'Kampong Belimbing'],
                            ['name' => 'Kampong Buang Tawar'],
                            ['name' => 'Kampong Dato Gandi'],
                            ['name' => 'Kampong Kota Batu'],
                            ['name' => 'Kampong Menunggol'],
                            ['name' => 'Kampong Pelambayan'],
                            ['name' => 'Kampong Pintu Malim'],
                            ['name' => 'Kampong Pudak'],
                            ['name' => 'Kampong Riong'],
                            ['name' => 'Kampong Serdang'],
                            ['name' => 'Kampong Subok'],
                            ['name' => 'Kampong Sungai Belukut'],
                            ['name' => 'Kampong Sungai Besar'],
                            ['name' => 'Kampong Sungai Lampai'],
                            ['name' => 'Kampong Sungai Matan'],
                            ['name' => 'Kampong Sungai Bunga'],
                            ['name' => 'Pulau Sibungor'],
                            ['name' => 'Pulau Baru-Baru'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Lumapas',
                        'village' => [
                            ['name' => 'Kampong Baong'],
                            ['name' => 'Kampong Buang Sakar'],
                            ['name' => 'Kampong Buang Tekurok'],
                            ['name' => 'Kampong Kasat'],
                            ['name' => 'Kampong Kilugus'],
                            ['name' => 'Kampong Lumapas'],
                            ['name' => 'Kampong Lupak Luas'],
                            ['name' => 'Kampong Tarap Bau'],
                            ['name' => 'Kampong Sungai Asam'],
                            ['name' => 'Kampong Panchor'],
                            ['name' => 'Kampong Putat'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Mentiri',
                        'village' => [
                            ['name' => 'Kampong Batu Marang'],
                            ['name' => 'Kampong Mentiri'],
                            ['name' => 'Kampong Pengkalan Sibabau'],
                            ['name' => 'Kampong Salar'],
                            ['name' => 'Kampong Sungai Buloh'],
                            ['name' => 'Kampong Tanah Jambu'],
                            ['name' => 'RPN Mentiri Area A'],
                            ['name' => 'RPN Mentiri Area B'],
                            ['name' => 'RPN Panchor Mengkubau'],
                            ['name' => 'Kampong Panchor'],
                            ['name' => 'Kampong Putat'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Pengkalan Batu',
                        'village' => [
                            ['name' => 'Kampong Batang Perhentian'],
                            ['name' => 'Kampong Batong'],
                            ['name' => 'Kampong Batu Ampar'],
                            ['name' => 'Kampong Bebatik'],
                            ['name' => 'Kampong Bebuloh'],
                            ['name' => 'Kampong Imang'],
                            ['name' => 'Kampong Junjongan'],
                            ['name' => 'Kampong Kuala Lurah'],
                            ['name' => 'Kampong Limau Manis'],
                            ['name' => 'Kampong Masin'],
                            ['name' => 'Kampong Panchor Murai'],
                            ['name' => 'Kampong Parit'],
                            ['name' => 'Kampong Pengkalan Batu'],
                            ['name' => 'Kampong Wasan'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Peramu',
                        'village' => [
                            ['name' => 'Kampong Bakut Berumput'],
                            ['name' => 'Kampong Bakut Pengiran Siraja Muda A'],
                            ['name' => 'Kampong Bakut Pengiran Siraja Muda B'],
                            ['name' => 'Kampong Lurong Sikuna'],
                            ['name' => 'Kampong Pekilong Muara'],
                            ['name' => 'Kampong Peramu'],
                            ['name' => 'Kampong Setia Pahlawan'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Saba',
                        'village' => [
                            ['name' => 'Kampong Saba Darat A'],
                            ['name' => 'Kampong Saba Darat B'],
                            ['name' => 'Kampong Saba Laut'],
                            ['name' => 'Kampong Saba Tengah'],
                            ['name' => 'Kampong Saba Ujong'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Sengkurong',
                        'village' => [
                            ['name' => 'Kampong Jerudong'],
                            ['name' => 'Kampong Katimahar'],
                            ['name' => 'Kampong Kulapis'],
                            ['name' => 'Kampong Lugu'],
                            ['name' => 'Kampong Mulaut'],
                            ['name' => 'Kampong Pasai'],
                            ['name' => 'Kampong Peninjau'],
                            ['name' => 'Kampong Selayun'],
                            ['name' => 'Kampong Sengkurong A'],
                            ['name' => 'Kampong Sengkurong B'],
                            ['name' => 'Kampong Tagap'],
                            ['name' => 'Kampong Tanjong Nangka'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Serasa',
                        'village' => [
                            ['name' => 'Muara Town'],
                            ['name' => 'Kampong Kapok'],
                            ['name' => 'Kampong Meragang'],
                            ['name' => 'RPN Meragang'],
                            ['name' => 'Kampong Sabun'],
                            ['name' => 'Kampong Serasa'],
                            ['name' => 'Perpindahan Serasa'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Sungai Kebun',
                        'village' => [
                            ['name' => 'Kampong Bolkiah A'],
                            ['name' => 'Kampong Bolkiah B'],
                            ['name' => 'Kampong Setia A'],
                            ['name' => 'Kampong Setia B'],
                            ['name' => 'Kampong Sungai Siamas'],
                            ['name' => 'Kampong Ujong Kelinik'],
                            ['name' => 'Kampong Sungai Kebun'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Sungai Kedayan',
                        'village' => [
                            ['name' => 'Kampong Ujong Tanjong'],
                            ['name' => 'Kampong Bukit Salat'],
                            ['name' => 'Kampong Kuala Peminyak'],
                            ['name' => 'Kampong Pemancha Lama'],
                            ['name' => 'Kampong Sumbiling Lama'],
                            ['name' => 'Kampong Sungai Kedayan A'],
                            ['name' => 'Kampong Sungai Kedayan B'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Tamoi',
                        'village' => [
                            ['name' => 'Kampong Limbongan'],
                            ['name' => 'Kampong Pengiran Bendahara Lama'],
                            ['name' => 'Kampong Pengiran Kerma Indera Lama'],
                            ['name' => 'Kampong Pengiran Tajuddin Hitam'],
                            ['name' => 'Kampong Tamoi Tengah'],
                            ['name' => 'Kampong Tamoi Ujong'],
                            ['name' => 'Kampong Ujong Bukit'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Tutong',
                'mukim' => [
                    [
                        'name' => 'Mukim Keriam',
                        'village' => [
                            ['name' => 'Kampong Bukit Panggal'],
                            ['name' => 'Kampong Ikas'],
                            ['name' => 'Kampong Keriam'],
                            ['name' => 'Kampong Kupang'],
                            ['name' => 'Kampong Luagan Dudok'],
                            ['name' => 'Kampong Maraburong'],
                            ['name' => 'Kampong Sinaut'],
                            ['name' => 'Kampong Sungai Kelugos'],
                            ['name' => 'Padang Tembak Binturan'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kiudang',
                        'village' => [
                            ['name' => 'Kampong Bakiau'],
                            ['name' => 'Kampong Batang Mitus'],
                            ['name' => 'Kampong Birau'],
                            ['name' => 'Kampong Kebia'],
                            ['name' => 'Kampong Kiudang'],
                            ['name' => 'Kampong Luagan Timbaran'],
                            ['name' => 'Kampong Mungkom'],
                            ['name' => 'Kampong Pad Nunok'],
                            ['name' => 'Kampong Pangkalan Mau'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Lamunin ',
                        'village' => [
                            ['name' => 'Kampong Bintudoh'],
                            ['name' => 'Kampong Biong'],
                            ['name' => 'Kampong Bukit Bang Dalam'],
                            ['name' => 'Kampong Bukit Barun'],
                            ['name' => 'Kampong Bukit Sulang'],
                            ['name' => 'Kampong Kuala Abang'],
                            ['name' => 'Kampong Lamunin'],
                            ['name' => 'Kampong Layong'],
                            ['name' => 'Kampong Menengah'],
                            ['name' => 'Kampong Panchong'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Pekan Tutong',
                        'village' => [
                            ['name' => 'Bukit Bendera'],
                            ['name' => 'Kampong Kandang'],
                            ['name' => 'Kampong Kuala Tutong'],
                            ['name' => 'Kampong Panchor Dulit'],
                            ['name' => 'Kampong Panchor Papan'],
                            ['name' => 'Kampong Penabai'],
                            ['name' => 'Kampong Penanjong'],
                            ['name' => 'Kampong Petani'],
                            ['name' => 'Kampong Sengkarai'],
                            ['name' => 'Kampong Serambangun'],
                            ['name' => 'Kampong Tanah Burok'],
                            ['name' => 'Tutong Kem'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Rambai',
                        'village' => [
                            ['name' => 'Bukit Ladan Forest Reserve'],
                            ['name' => 'Kampong Bedawan'],
                            ['name' => 'Kampong Belabau'],
                            ['name' => 'Kampong Benutan'],
                            ['name' => 'Kampong Kuala Ungar'],
                            ['name' => 'Kampong Lalipo'],
                            ['name' => 'Kampong Merimbun'],
                            ['name' => 'Kampong Rambai'],
                            ['name' => 'Kampong Supon Besar'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Tanjong Maya',
                        'village' => [
                            ['name' => 'Kampong Bangunggos'],
                            ['name' => 'Kampong Bukit Sibut'],
                            ['name' => 'Kampong Bukit Udal'],
                            ['name' => 'Kampong Liulon'],
                            ['name' => 'Kampong Lubok Pulau'],
                            ['name' => 'Kampong Pemadang'],
                            ['name' => 'Kampong Penapar'],
                            ['name' => 'Kampong Sebakit'],
                            ['name' => 'Kampong Tanjong Maya'],
                            ['name' => 'Kampong Tanjong Panjang'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Telisai',
                        'village' => [
                            ['name' => 'Kampong Bukit Beruang'],
                            ['name' => 'Kampong Bukit Pasir'],
                            ['name' => 'Kampong Danau'],
                            ['name' => 'Kampong Keramut'],
                            ['name' => 'Kampong Panapar-Danau'],
                            ['name' => 'Kampong Pangkalan Dalai'],
                            ['name' => 'Kampong Penyatang'],
                            ['name' => 'Kampong Sungai Paku'],
                            ['name' => 'Kampong Telamba'],
                            ['name' => 'Kampong Telisai'],
                            ['name' => 'Kampong Tumpuan Ugas'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Ukong',
                        'village' => [
                            ['name' => 'Kampong Bukit'],
                            ['name' => 'Kampong Long Mayan'],
                            ['name' => 'Kampong Pak Bidang'],
                            ['name' => 'Kampong Pengkalan Raan'],
                            ['name' => 'Kampong Sungai Damit Pemadang'],
                            ['name' => 'Kampong Ukong'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Belait',
                'mukim' => [
                    [
                        'name' => 'Mukim Bukit Sawat',
                        'village' => [
                            ['name' => 'Kampong Bisut'],
                            ['name' => 'Kampong Bukit Kandol'],
                            ['name' => 'Kampong Bukit Sawat'],
                            ['name' => 'Kampong Melayan'],
                            ['name' => 'Kampong Merangking'],
                            ['name' => 'Kampong Merangking Hilir'],
                            ['name' => 'Kampong Merangking Ulu'],
                            ['name' => 'Kampong Sungai Mau'],
                            ['name' => 'Kampong Pulau Apil'],
                            ['name' => 'Kampong Tarap'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kuala Balai',
                        'village' => [
                            ['name' => 'Kampong Kajitan'],
                            ['name' => 'Kampong Kuala Balai'],
                            ['name' => 'Kampong Lubuk Lanyap'],
                            ['name' => 'Kampong Lubuk Tapang'],
                            ['name' => 'Kampong Pengalayan'],
                            ['name' => 'Kampong Penyarap'],
                            ['name' => 'Kampong Sungai Damit'],
                            ['name' => 'Kampong Sungai Lutong'],
                            ['name' => 'Kampong Tanjung Ranggas'],
                            ['name' => 'Kampong Tanjung Sudai'],
                            ['name' => 'Kampong Tugong'],
                            ['name' => 'Kampong Sungai Mendaram'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Kuala Belait',
                        'village' => [
                            ['name' => 'Kampong Mumong A'],
                            ['name' => 'Kampong Mumong B'],
                            ['name' => 'Kampong Pandan A'],
                            ['name' => 'Kampong Pandan B'],
                            ['name' => 'Kampong Pandan C'],
                            ['name' => 'Kampong Sungai Teraban'],
                            ['name' => 'Kuala Belait'],
                            ['name' => 'Kampong Sungai Duhon'],
                            ['name' => 'Kampong Melayu Asli'],
                            ['name' => 'Kampong China'],
                            ['name' => 'Kampong Sungai Melilit'],
                            ['name' => 'Kampong Rasau'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Labi',
                        'village' => [
                            ['name' => 'Kampong Bukit Puan'],
                            ['name' => 'Kampong Gatas'],
                            ['name' => 'Kampong Kenapol'],
                            ['name' => 'Kampong Labi'],
                            ['name' => 'Kampong Labi Lama'],
                            ['name' => 'Kampong Mendaram Kecil'],
                            ['name' => 'Kampong Rampayoh'],
                            ['name' => 'Kampong Ratan'],
                            ['name' => 'Kampong Sungai Petai'],
                            ['name' => 'Kampong Tanajor'],
                            ['name' => 'Kampong Tapang Lupak'],
                            ['name' => 'Kampong Teraja'],
                            ['name' => 'Kampong Terawan'],
                            ['name' => 'Kampong Terunan'],
                            ['name' => 'Kampong Labi I'],
                            ['name' => 'Kampong Labi II'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Liang',
                        'village' => [
                            ['name' => 'Kampong Agis-Agis'],
                            ['name' => 'Kampong Keluyoh'],
                            ['name' => 'Kampong Lilas'],
                            ['name' => 'Kampong Lumut'],
                            ['name' => 'Kampong Lumut Tersusun'],
                            ['name' => 'Kampong Perumpong'],
                            ['name' => 'Kampong Sungai Bakong'],
                            ['name' => 'Kampong Sungai Gana'],
                            ['name' => 'Kampong Sungai Kang'],
                            ['name' => 'Kampong Sungai Kuru'],
                            ['name' => 'Kampong Sungai Lalit'],
                            ['name' => 'Kampong Sungai Liang'],
                            ['name' => 'Kampong Sungai Tali'],
                            ['name' => 'Kampong Sungai Taring'],
                            ['name' => 'Kampong Tunggulian'],
                            ['name' => 'Perkhemahan Lumut'],
                            ['name' => 'RPN Lumut Area 1'],
                            ['name' => 'RPN Lumut Area 2'],
                            ['name' => 'Kampong Lumut I'],
                            ['name' => 'Kampong Lumut II'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Melilas',
                        'village' => [
                            ['name' => 'Kampong Melilas'],
                            ['name' => 'Kampong Bukit Tuding'],
                            ['name' => 'Kampong Bang Garang'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Seria',
                        'village' => [
                            ['name' => 'Kampong Lorong Tiga Selatan'],
                            ['name' => 'Kampong Sungai Bera'],
                            ['name' => 'Kampong Panaga'],
                            ['name' => 'RPN Lorong Tengah'],
                            ['name' => 'Seria Town Area 1'],
                            ['name' => 'Seria Town Area 2'],
                            ['name' => 'Kampong Perakong'],
                            ['name' => 'Kampong Jabang'],
                            ['name' => 'Kampong Badas'],
                            ['name' => 'Kampong Anduki'],
                            ['name' => 'Ibu Pejabat Shell'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Sukang',
                        'village' => [
                            ['name' => 'Kampong Apak-Apak'],
                            ['name' => 'Kampong Dungun'],
                            ['name' => 'Kampong Kukub'],
                            ['name' => 'Kampong Sukang'],
                            ['name' => 'Kampong Sungai Hilir'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Temburong',
                'mukim' => [
                    [
                        'name' => 'Mukim Amo',
                        'village' => [
                            ['name' => 'Kampong Amo A'],
                            ['name' => 'Kampong Amo B'],
                            ['name' => 'Kampong Amo C'],
                            ['name' => 'Kampong Batang Duri'],
                            ['name' => 'Kampong Belaban'],
                            ['name' => 'Kampong Biang'],
                            ['name' => 'Kampong Parit'],
                            ['name' => 'Kampong Selangan'],
                            ['name' => 'Kampong Sibulu'],
                            ['name' => 'Kampong Sibut'],
                            ['name' => 'Kampong Sumbiling Baru'],
                            ['name' => 'Kampong Sumbiling Lama'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Bangar',
                        'village' => [
                            ['name' => 'Pekan Bangar'],
                            ['name' => 'Kampong Bang Bulan'],
                            ['name' => 'Kampong Batang Tuau'],
                            ['name' => 'Kampong Batu Bejarah'],
                            ['name' => 'Kampong Belingos'],
                            ['name' => 'Kampong Gadong'],
                            ['name' => 'Kampong Kinalog'],
                            ['name' => 'Kampong Lagau'],
                            ['name' => 'Kampong Menengah'],
                            ['name' => 'Kampong Parit Belayang'],
                            ['name' => 'Kampong Piungan'],
                            ['name' => 'Kampong Puni'],
                            ['name' => 'Kampong Semamang'],
                            ['name' => 'Kampong Subok'],
                            ['name' => 'Kampong Seri Tanjong Belayang'],
                            ['name' => 'Kampong Sungai Tanam'],
                            ['name' => 'Kampong Sungai Tanit'],
                            ['name' => 'Kampong Sungai Sulok'],
                            ['name' => 'Kampong Ujong Jalan'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Batu Apoi',
                        'village' => [
                            ['name' => 'Kampong Batu Apoi'],
                            ['name' => 'Kampong Gadong Baru'],
                            ['name' => 'Kampong Lakiun'],
                            ['name' => 'Kampong Lamaling'],
                            ['name' => 'Kampong Luagan'],
                            ['name' => 'Kampong Negalang Ering'],
                            ['name' => 'Kampong Negalang Unat'],
                            ['name' => 'Kampong Peliunan'],
                            ['name' => 'Kampong Rebada'],
                            ['name' => 'Kampong Selapon'],
                            ['name' => 'Kampong Selilit'],
                            ['name' => 'Kampong Sekurop'],
                            ['name' => 'Kampong Simbatang'],
                            ['name' => 'Kampong Sungai Radang'],
                            ['name' => 'Kampong Tanjong Bungar'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Bokok',
                        'village' => [
                            ['name' => 'Kampong Bakarat'],
                            ['name' => 'Kampong Belais Besar'],
                            ['name' => 'Kampong Belais Kecil'],
                            ['name' => 'Kampong Bokok'],
                            ['name' => 'Kampong Buda-Buda'],
                            ['name' => 'Kampong Kenua'],
                            ['name' => 'Kampong Lepong Baru'],
                            ['name' => 'Kampong Maniup'],
                            ['name' => 'Kampong Paya Bagangan'],
                            ['name' => 'Kampong Rataie'],
                            ['name' => 'Kampong Semabat'],
                            ['name' => 'Kampong Simbatang'],
                            ['name' => 'Kampong Temada'],
                            ['name' => 'Kampong Perpindahan Rataie'],
                            ['name' => 'Kampong Rakyat Jati'],
                        ],
                    ],
                    [
                        'name' => 'Mukim Labu',
                        'village' => [
                            ['name' => 'Kampong Labu Estate'],
                            ['name' => 'Kampong Piasau-Piasau'],
                            ['name' => 'Kampong Senukoh'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Government Departments',
                'mukim' => [
                    [
                        'name' => 'Jabatan Perdana Menteri',
                        'village' => [
                            ['name' => 'Adat Istiadat Negara'],
                            ['name' => 'JPM (Bangunan Setiausaha Kerajaan)'],
                            ['name' => 'JPM (Istana Nurul Iman)'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Hal Ehwal Dalam Negeri',
                        'village' => [
                            ['name' => 'Jabatan Bandaran (Bandar Seri Begawan)'],
                            ['name' => 'Jabatan Buruh'],
                            ['name' => 'Jabatan Daerah Temburong'],
                            ['name' => 'Jabatan Daerah Tutong'],
                            ['name' => 'Jabatan Imigresen dan Pendaftaran'],
                            ['name' => 'Jabatan Penjara'],
                            ['name' => 'Jabatan Perkhidmatan Bomba'],
                            ['name' => 'Kementerian Hal Ehwal Dalam Negeri'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Hal Ehwal Luar Negeri',
                        'village' => [
                            ['name' => 'Kementerian Hal Ehwal Luar Negeri'],
                            ['name' => 'Pusat Persidangan Antarabangsa'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Hal Ehwal Ugama',
                        'village' => [
                            ['name' => 'Institut Pengajian Islam Brunei Darussalam'],
                            ['name' => 'Jabatan Hal Ehwal Masjid'],
                            ['name' => 'Jabatan Hal Ehwal Syariah'],
                            ['name' => 'Jabatan Urusan Haji'],
                            ['name' => 'Kementerian Hal Ehwal Ugama'],
                            ['name' => 'Pejabat Kadi Besar'],
                            ['name' => 'Pejabat Pengajian Islam'],
                            ['name' => 'Pusat Dakwah Islamiah'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Kesihatan',
                        'village' => [
                            ['name' => 'Hospital RIPAS'],
                            ['name' => 'Jabatan Perubatan dan Kesihatan'],
                            ['name' => 'Kementerian Kesihatan'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Kewangan',
                        'village' => [
                            ['name' => 'Agensi Pelaburan Brunei'],
                            ['name' => 'Jabatan Perbendaharaan'],
                            ['name' => 'Jabatan Teknologi Maklumat dan Stor Negara'],
                            ['name' => 'Kastam dan Eksais Diraja'],
                            ['name' => 'Kementerian Kewangan'],
                            ['name' => 'Lembaga Mata Wang'],
                            ['name' => 'Perancangan dan Kemajuan Ekonomi'],
                            ['name' => 'Tabung Amanah Pekerja'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Pembangunan',
                        'village' => [
                            ['name' => 'Jabatan Kemajuan Perumahan'],
                            ['name' => 'Jabatan Kerja Raya'],
                            ['name' => 'Jabatan Perancangan Bandar dan Desa'],
                            ['name' => 'Jabatan Perkhidmatan Eletrik'],
                            ['name' => 'Kementerian Pembangunan'],
                            ['name' => 'Pejabat Tanah'],
                            ['name' => 'Pejabat Ukur'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Pendidikan',
                        'village' => [
                            ['name' => 'Jabatan Kenaziran Sekolah-Sekolah'],
                            ['name' => 'Jabatan Kurikulum'],
                            ['name' => 'Jabatan Pendidikan Teknik'],
                            ['name' => 'Jabatan Pentadbiran dan Perkhidmatan-Perkhidmatan'],
                            ['name' => 'Jabatan Peperiksaan'],
                            ['name' => 'Jabatan Perancangan dan Pemeliharaan Bangunan dan Kawasan'],
                            ['name' => 'Jabatan Perkembangan Kurikulum'],
                            ['name' => 'Jabatan Sekolah-Sekolah'],
                            ['name' => 'Kementerian Pendidikan'],
                            ['name' => 'Universiti Brunei Darussalam'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Perhubungan',
                        'village' => [
                            ['name' => 'Jabatan Laut'],
                            ['name' => 'Jabatan Pelabuhan-Pelabuhan'],
                            ['name' => 'Jabatan Penerbangan Awam'],
                            ['name' => 'Jabatan Pengangkutan Darat'],
                            ['name' => 'Jabatan Perkhidmatan Pos'],
                            ['name' => 'Jabatan Telekom'],
                            ['name' => 'Kementerian Perhubungan'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Perindustrian dan Sumber-Sumber Utama',
                        'village' => [
                            ['name' => 'Badan Kemajuan Industri Brunei (BINA)'],
                            ['name' => 'Jabatan Perhutanan'],
                            ['name' => 'Jabatan Perikanan'],
                            ['name' => 'Jabatan Pertanian'],
                            ['name' => 'JKementerian Perindustrian dan Sumber-Sumber Utama'],
                            ['name' => 'Semaun Holdings'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Pertahanan',
                        'village' => [
                            ['name' => 'Angkatan Bersenjata Diraja Brunei'],
                            ['name' => 'Unit Gurka Simpanan'],
                        ],
                    ],
                    [
                        'name' => 'Kementerian Undang-Undang',
                        'village' => [
                            ['name' => 'Jabatan Kehakiman'],
                            ['name' => 'Jabatan Percetakan'],
                            ['name' => 'Jabatan Undang-Undang'],
                            ['name' => 'Kementerian Undang-Undang'],
                        ],
                    ],
                ],
            ],
        ];

        foreach ($districts as $district) {
            $district_row = District::create([
                'name' => $district['name'], // 1st iteration Brunei-muara

            ]);
            foreach ($district['mukim'] as $mukim) {
                $mukim_row = Mukim::create([
                    'name' => $mukim['name'],
                    'district_id' => $district_row->id,
                ]);
                foreach ($mukim['village'] as $village) {
                    $village_row = Village::create([
                        'name' => $village['name'],
                        'mukim_id' => $mukim_row->id,
                    ]);
                }
            }
        }
    }
}
